name: Merging into Development Branch
'on':
  push:
    branches:
      - development
env:
  CI: false
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm run test
